"""Build the local mappedRoom review page from the current comparison report."""
from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]/'mappedRoom'
r = json.loads((root/'review/comparison.json').read_text())
lookup = {(row['room'],row['shadowLights']): row for row in r['offlineCycles']}
rows = ''.join(f"<tr><td>{n}</td><td>{lookup['baseline',n]['medianSeconds']:.3f}</td><td>{lookup['mappedRoom',n]['medianSeconds']:.3f}</td></tr>"
               for n in [0,1,2,4,8,16,32,64] if ('baseline',n) in lookup and ('mappedRoom',n) in lookup)
images = [(f'{room} · {count} shadow lights', f'{room}-{count}-lights.png') for count in [8,0] for room in ['baseline','mappedRoom'] if (room,count) in lookup]
figures = ''.join(f'<figure><img src="{file}" alt="{title}"><figcaption>{title}</figcaption></figure>' for title,file in images)
views = ''.join(f'<figure><a href="../output/cutaway-{v}.png"><img src="../output/cutaway-{v}.png" alt="mappedRoom {v} cutaway"></a><figcaption>{v}</figcaption></figure>' for v in ['front-left','front-right','rear-right','rear-left'] if (root/f'output/cutaway-{v}.png').exists())
html = f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>mappedRoom · room lighting review</title><style>body{{margin:0;background:#101820;color:#e6edf3;font:16px/1.6 system-ui}}main{{max-width:1200px;margin:auto;padding:36px}}h1{{font-size:48px;line-height:1.1}}h2{{margin-top:42px}}a{{color:#79d6df}}.grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}}figure{{margin:0;background:#202c38;border-radius:12px;overflow:hidden}}img{{width:100%;display:block}}figcaption{{padding:12px 18px}}.note{{border-left:4px solid #efb554;padding:14px 20px;background:#24313b}}table{{width:100%;border-collapse:collapse}}td,th{{padding:8px 18px;text-align:left;border-bottom:1px solid #36434f}}small{{color:#b6c5d2}}@media(max-width:700px){{.grid{{grid-template-columns:1fr}}main{{padding:20px}}}}</style><main><small>VENUE VOLUME · CLASSROOM MATERIAL STUDY</small><h1>mappedRoom</h1><p>Photo-derived surface detail on the original opaque room mesh. Dynamic lighting and occlusion come first.</p><p><a href="../output/environment.usdz">USDZ</a> · <a href="../output/mappedRoom.blend">Blender</a> · <a href="../README.md">Build &amp; validation notes</a> · <a href="comparison.json">Raw comparison results</a></p><p class="note">Desktop proof only. Vision Pro maximum smooth light count is unmeasured. The app keeps eight shadow beams by default and provides higher budgets for device profiling.</p><h2>Same lighting, same geometry</h2><p>18,744 triangles · 68 mesh chunks · 13 materials. Six shared textures add about 0.55 MiB to the package, with roughly 4 MiB estimated RGBA8 texture memory including mipmaps. Surface detail is approximate; unique wall graphics are not mapped.</p><div class="grid">{figures}</div><h2>Review corners</h2><div class="grid">{views}</div><h2>Offline render cost</h2><p>Blender Cycles · median of three renders after warmup. Units are seconds per still render, <strong>not headset frame times or FPS</strong>. Fixture rigs are absent. Small differences include measurement noise. See the JSON for the renderer, device and settings; no timing rows appear after a structural-only rebuild.</p><table><thead><tr><th>Shadow lights</th><th>Original seconds</th><th>Mapped seconds</th></tr></thead><tbody>{rows}</tbody></table></main></html>'''
(root/'review/index.html').write_text(html)
