export const screens = [
  [
    "sign-in",
    "Sign in",
    "Workspace",
    "F01",
    "Identify the operator and recover access.",
  ],
  [
    "workspace",
    "Create workspace",
    "Workspace",
    "F01",
    "Establish the company workspace and first team.",
  ],
  [
    "shows",
    "All shows",
    "Workspace",
    "F02",
    "Find, duplicate, archive, or create a show.",
  ],
  [
    "new-show",
    "Create show",
    "Workspace",
    "F02",
    "Name the production and set its starting configuration.",
  ],
  [
    "overview",
    "Show overview",
    "Show",
    "F02",
    "Understand readiness and continue the next production task.",
  ],
  [
    "templates",
    "Configuration templates",
    "Show",
    "F03",
    "Manage reusable rig configurations inside this show.",
  ],
  [
    "template-detail",
    "Template details",
    "Show",
    "F03",
    "Inspect a version, its drawing, inventory, and dependent venues.",
  ],
  [
    "template-editor",
    "Template drawing",
    "Show",
    "F04",
    "Arrange equipment over a saved technical drawing.",
  ],
  [
    "inventory",
    "Equipment inventory",
    "Show",
    "F05",
    "Track lighting and non-lighting production equipment.",
  ],
  [
    "equipment",
    "Equipment details",
    "Show",
    "F05",
    "Edit quantity, capability, ownership, and equipment metadata.",
  ],
  [
    "library",
    "Fixture library",
    "Show",
    "F06",
    "Find fixture profiles and modes before patching.",
  ],
  [
    "fixture",
    "Fixture profile",
    "Show",
    "F06",
    "Inspect channel capabilities, ranges, defaults, and compatibility.",
  ],
  [
    "venues",
    "Venues",
    "Venue",
    "F07",
    "Compare venue-specific configurations and readiness.",
  ],
  [
    "new-venue",
    "Create venue",
    "Venue",
    "F07",
    "Seed a venue from a specific template revision.",
  ],
  [
    "venue-detail",
    "Venue overview",
    "Venue",
    "F07",
    "Review the local configuration and prepare for load-in.",
  ],
  [
    "venue-layout",
    "Venue drawing",
    "Venue",
    "F04",
    "Adapt the inherited rig to the venue footprint.",
  ],
  [
    "patch",
    "DMX patch",
    "Venue",
    "F08",
    "Map logical fixtures to addresses with conflict detection.",
  ],
  [
    "overrides",
    "Compare overrides",
    "Venue",
    "F09",
    "Inspect and reset differences without losing show defaults.",
  ],
  [
    "presets",
    "Preset library",
    "Program",
    "F10",
    "Reuse parameter looks across repeated fixture groups.",
  ],
  [
    "preset-editor",
    "Preset editor",
    "Program",
    "F10",
    "Program parameters and inspect venue-resolved values.",
  ],
  [
    "cues",
    "Cue library",
    "Program",
    "F11",
    "Manage named show states independently from running order.",
  ],
  [
    "cue-editor",
    "Cue editor",
    "Program",
    "F11",
    "Assign presets to fixture roles and define transitions.",
  ],
  [
    "scripts",
    "Scripts",
    "Program",
    "F12",
    "Choose an expected cue sequence and revision.",
  ],
  [
    "script-editor",
    "Script editor",
    "Program",
    "F12",
    "Order cue references, repeats, notes, and advance policies.",
  ],
  [
    "rehearsal",
    "Rehearsal",
    "Operate",
    "F13",
    "Step through the venue-resolved script with simulated output.",
  ],
  [
    "live",
    "Live console",
    "Operate",
    "F13",
    "Operate the touch desk: select fixtures, adjust live values, call/restart cues, follow MIDI, and detach a synchronized console.",
  ],
  [
    "outputs",
    "Output connections",
    "Operate",
    "F14",
    "Pair a bridge and route logical universes to network outputs.",
  ],
  [
    "universe",
    "Universe monitor",
    "Operate",
    "F14",
    "Inspect individual slot values and output freshness.",
  ],
  [
    "preflight",
    "Preflight",
    "Operate",
    "F13",
    "Resolve blocking readiness issues before arming.",
  ],
  [
    "recovery",
    "Connection recovery",
    "Operate",
    "F14",
    "Reconcile stale state and explicitly resume after a disconnect.",
  ],
  [
    "assets",
    "Files & drawings",
    "Manage",
    "F04",
    "Manage original CAD assets, previews, and revisions.",
  ],
  [
    "activity",
    "Activity & versions",
    "Manage",
    "F15",
    "Audit edits and restore a reviewed historical revision.",
  ],
  [
    "team",
    "Team & access",
    "Manage",
    "F01",
    "Invite collaborators with explicit workspace/show permissions.",
  ],
  [
    "settings",
    "Show settings",
    "Manage",
    "F02",
    "Configure identity, defaults, export, and archive behavior.",
  ],
  [
    "billing",
    "Plan & billing",
    "Manage",
    "F01",
    "Inspect subscription boundaries without interrupting an active run.",
  ],
].map(([id, title, section, feature, purpose], index) => ({
  id,
  title,
  section,
  feature,
  purpose,
  number: String(index + 1).padStart(2, "0"),
}));

export const fixtureRows = [
  {
    id: "FX-001",
    name: "Upstage wash 01",
    model: "VV RGBW Wash",
    role: "Upstage wash",
    mode: "8 channel",
    address: 1,
    universe: 1,
    footprint: 8,
  },
  {
    id: "FX-002",
    name: "Upstage wash 02",
    model: "VV RGBW Wash",
    role: "Upstage wash",
    mode: "8 channel",
    address: 9,
    universe: 1,
    footprint: 8,
  },
  {
    id: "FX-003",
    name: "Upstage wash 03",
    model: "VV RGBW Wash",
    role: "Upstage wash",
    mode: "8 channel",
    address: 17,
    universe: 1,
    footprint: 8,
  },
  {
    id: "FX-004",
    name: "Upstage wash 04",
    model: "VV RGBW Wash",
    role: "Upstage wash",
    mode: "8 channel",
    address: 25,
    universe: 1,
    footprint: 8,
  },
  {
    id: "FX-005",
    name: "Front profile 01",
    model: "VV Profile Spot",
    role: "Front key",
    mode: "16 channel",
    address: 33,
    universe: 1,
    footprint: 16,
  },
  {
    id: "FX-006",
    name: "Front profile 02",
    model: "VV Profile Spot",
    role: "Front key",
    mode: "16 channel",
    address: 49,
    universe: 1,
    footprint: 16,
  },
  {
    id: "FX-007",
    name: "Side beam 01",
    model: "VV Moving Beam",
    role: "Side beams",
    mode: "16 channel",
    address: 65,
    universe: 1,
    footprint: 16,
  },
  {
    id: "FX-008",
    name: "Side beam 02",
    model: "VV Moving Beam",
    role: "Side beams",
    mode: "16 channel",
    address: 81,
    universe: 1,
    footprint: 16,
  },
];
export const presetRows = [
  {
    name: "House open",
    type: "Atmosphere",
    color: "#e8be7a",
    intensity: 65,
    count: 6,
  },
  {
    name: "Midnight blue",
    type: "Color",
    color: "#7386ee",
    intensity: 75,
    count: 4,
  },
  {
    name: "Amber silhouette",
    type: "Color",
    color: "#e29657",
    intensity: 85,
    count: 3,
  },
  {
    name: "Soft front key",
    type: "Position + intensity",
    color: "#e8debc",
    intensity: 60,
    count: 5,
  },
  {
    name: "Violet bloom",
    type: "Color",
    color: "#bd82dd",
    intensity: 70,
    count: 2,
  },
  {
    name: "Full release",
    type: "Intensity",
    color: "#dce8e4",
    intensity: 100,
    count: 1,
  },
];
export const cueRows = [
  {
    id: "Q01",
    name: "House open",
    section: "Pre-show",
    preset: "House open",
    fade: 3,
    color: "#e8be7a",
  },
  {
    id: "Q02",
    name: "Into the blue",
    section: "Act I",
    preset: "Midnight blue",
    fade: 4,
    color: "#7386ee",
  },
  {
    id: "Q03",
    name: "First light",
    section: "Act I",
    preset: "Amber silhouette",
    fade: 2,
    color: "#e29657",
  },
  {
    id: "Q04",
    name: "Still / moving",
    section: "Act I",
    preset: "Soft front key",
    fade: 6,
    color: "#e8debc",
  },
  {
    id: "Q05",
    name: "Violet hour",
    section: "Act II",
    preset: "Violet bloom",
    fade: 3,
    color: "#bd82dd",
  },
  {
    id: "Q06",
    name: "Afterglow",
    section: "Encore",
    preset: "Full release",
    fade: 5,
    color: "#dce8e4",
  },
];
